// Auto-generated by emails/compile.ts — do not edit manually.
// Source: emails/formInvitation.mjml
// To modify this template, edit the MJML source and run: pnpm email:compile

export const formInvitationTemplate = `<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
      <!--[if !mso]><!-->
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" type="text/css">
        <style type="text/css">
          @import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700);
        </style>
      <!--<![endif]-->

    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
    </style>
    
    
  
    
    
    
  </head>
  <body style="word-spacing:normal;background-color:#f8fafc;">
    
    
      <div
         aria-roledescription="email" style="background-color:#f8fafc;" role="article" lang="und" dir="auto"
      >
        <!-- Header -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#141e30" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#141e30;background-color:#141e30;margin:0px auto;max-width:600px;border-radius:16px 16px 0 0;overflow:hidden;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#141e30;background-color:#141e30;width:100%;border-collapse:separate;"
        >
          <tbody>
            <tr>
              <td
                 style="border-radius:16px 16px 0 0;direction:ltr;font-size:0px;padding:32px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:536px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:22px;font-weight:500;letter-spacing:0.02em;line-height:1.6;text-align:left;color:white;"
      >SJHAS, Inc.</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:6px 0 0 0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:13px;letter-spacing:0.04em;line-height:1.6;text-align:left;color:rgba(255,255,255,0.7);"
      >Accounting &amp; Tax Services</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Body -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="body-section-outlook" role="presentation" style="width:600px;" width="600" bgcolor="#ffffff" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  class="body-section" style="background:#ffffff;background-color:#ffffff;margin:0px auto;max-width:600px;border-radius:0 0 16px 16px;overflow:hidden;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff;background-color:#ffffff;width:100%;border-collapse:separate;"
        >
          <tbody>
            <tr>
              <td
                 style="border-radius:0 0 16px 16px;direction:ltr;font-size:0px;padding:32px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:536px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          <!-- Greeting -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 8px 0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:16px;font-weight:500;line-height:1.6;text-align:left;color:#0f172a;"
      >Hi {{displayName}},</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 24px 0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:15px;line-height:1.7;text-align:left;color:#475569;"
      >We have a form ready for you to complete. Please click the button below to get started.</div>
    
                </td>
              </tr>
            <!-- Custom Message (may be empty) -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 24px 0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:15px;line-height:1.7;text-align:left;color:#475569;"
      >{{customMessage}}</div>
    
                </td>
              </tr>
            <!-- Form Info Card -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 28px 0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:13px;line-height:1.6;text-align:left;color:#374151;"
      ><div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px;">
            <p style="color: #0f172a; font-size: 15px; font-weight: 500; margin: 0 0 4px 0;">{{formTitle}}</p>
            {{formDescription}}
          </div></div>
    
                </td>
              </tr>
            <!-- CTA Button -->
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 0 28px 0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="#243b55" role="presentation" style="border:none;border-radius:12px;cursor:auto;mso-padding-alt:14px 36px;background:#243b55;" valign="middle"
            >
              <a
                 href="{{formUrl}}" style="display:inline-block;background:#243b55;color:white;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:15px;font-weight:500;line-height:120%;letter-spacing:0.02em;margin:0;text-decoration:none;text-transform:none;padding:14px 36px;mso-padding-alt:0px;border-radius:12px;" target="_blank"
              >
                Open Form
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            <!-- Fallback Link -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 0 0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:13px;line-height:1.6;text-align:left;color:#94a3b8;"
      >Or copy this link: <a href="{{formUrl}}" style="color: #243b55;">{{formUrl}}</a></div>
    
                </td>
              </tr>
            <!-- Divider -->
              <tr>
                <td
                   align="center" style="font-size:0px;padding:28px 0 20px 0;word-break:break-word;"
                >
                  
      <p
         style="border-top:solid 1px #e2e8f0;font-size:1px;margin:0px auto;width:100%;"
      >
      </p>
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-top:solid 1px #e2e8f0;font-size:1px;margin:0px auto;width:536px;" role="presentation" width="536px" ><tr><td style="height:0;line-height:0;"> &nbsp;
</td></tr></table><![endif]-->
    
    
                </td>
              </tr>
            <!-- Footer -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;font-size:12px;line-height:1.6;text-align:left;color:#94a3b8;"
      >This email was sent by SJHAS, Inc. If you have questions, reply to this email or call (607) 216-8033.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
    
  </body>
</html>
  `
