/**
 * Compiles MJML source files into TypeScript template modules.
 *
 * Usage: pnpm email:compile
 *
 * This reads each .mjml file in this directory, compiles it to HTML,
 * and writes a TypeScript file to server/utils/emails/templates/.
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { resolve, basename } from 'path'
import mjml2html from 'mjml'

const emailsDir = resolve(import.meta.dirname!, '.')
const outputDir = resolve(import.meta.dirname!, '../server/utils/emails/templates')

const mjmlFiles = readdirSync(emailsDir).filter((f) => f.endsWith('.mjml'))

for (const file of mjmlFiles) {
  const name = basename(file, '.mjml')
  const mjmlSource = readFileSync(resolve(emailsDir, file), 'utf-8')

  const filePath = resolve(emailsDir, file)
  const { html, errors } = mjml2html(mjmlSource, {
    filePath,
    minify: false,
    validationLevel: 'soft',
  })

  if (errors.length > 0) {
    console.warn(`⚠ Warnings for ${file}:`)
    errors.forEach((e) => console.warn(`  - ${e.formattedMessage}`))
  }

  // Generate a unique export name like "formInvitationTemplate"
  const exportName = `${name}Template`

  const tsContent = `// Auto-generated by emails/compile.ts — do not edit manually.
// Source: emails/${file}
// To modify this template, edit the MJML source and run: pnpm email:compile

export const ${exportName} = \`${html.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`
`

  writeFileSync(resolve(outputDir, `${name}.ts`), tsContent, 'utf-8')
  console.log(`✓ ${file} → server/utils/emails/templates/${name}.ts`)
}

console.log('\nDone! All templates compiled.')
